# import time
#
from framework.basic_fiber import FiberTest
#
#
class TestFiberCC(FiberTest):
    debug = True
#     # start_fiber_config = {
#     #     "fiber_tlc_expiry_delta": 60
#     # }
#
    def test_0000(self):
        self.faucet(self.fiber1.account_private,0,self.fiber1.account_private,10000*100000000)
        self.open_channel(self.fiber1, self.fiber2, 1000 * 100000000, 1000 * 100000000,udt=self.get_account_udt_script(self.fiber1.account_private))
        self.fiber1.stop()
        self.fiber2.stop()

    def test_bbb(self):
        self.fiber1.stop()
        self.fiber1.start()
    def test_00021(self):
        self.fiber1.get_client().send_btc({
            "btc_pay_req":"lnbcrt10u1p5d3vz9pp5a0ur9jfsygaykujkymv9dax2t54dn28mz4jkk4ud9524zy8n6spsdq8w3jhxaqcqzzsxqyz5vqsp5se27w8ul3fystlc3vpmk85fecjke6022w3g3f7jssm0qr7c8haws9qxpqysgqzd3qr7h7fvmjxzklx2d6d29x5uzenpd4vwqxfsmunxmt5j03rs28e84f5qks03y0jpw66jtqvkzg9u9enggzrmxztyvq9uvlqfwlmzqpkger8p",
            "currency":"Fibd"
        })

    def test_00022(self):
        self.fiber1.get_client().get_receive_btc_order({
            "payment_hash": "0xebf832c930223a4b725626d856f4ca5d2ad9a8fb15656b578d2d155110f3d403"
        })

    def test_0002(self):
        self.fiber1.start()
        self.fiber2.start()
#         fiber3 = self.start_new_fiber(self.generate_account(1000))
#         self.open_channel(self.fiber1, self.fiber2, 1000 * 100000000, 1000 * 100000000)
#         self.open_channel(self.fiber2, fiber3, 1000 * 100000000, 1000 * 100000000)
#
#         channel_id = self.fiber1.get_client().list_channels({})["channels"][0]["channel_id"]
#
#     def test_122(self):
#         b = self.get_fiber_balance(self.fiber2)
#         self.fiber3 = self.start_new_mock_fiber("")
#         b1 = self.get_fiber_balance(self.fiber3)
#
#         print(b)
#         print(b1)
#
#     def test_bbb(self):
#         # self.fiber1.start()
#         self.fiber3 = self.start_new_mock_fiber("")
#         self.get_fibers_balance_message()
#
#     def test_bba(self):
#         # self.send_payment(self.fiber1, self.fiber2, 1)
#         self.fiber1.get_client().node_info()
#
#     def test_bbbbbb(self):
#         # self.fiber1.
#         fiber3 = self.start_new_mock_fiber("")
#         payment_preimage = self.generate_random_preimage()
#         invoice = fiber3.get_client().new_invoice({
#             "amount": hex(1 * 100000000),
#             "currency": "Fibd",
#             "description": "test invoice generated by node3",
#             "expiry": "0x6",
#             "final_cltv": "0xf",
#             "payment_preimage": payment_preimage,
#             # "udt_type_script": self.get_account_udt_script(
#             #     self.fiber1.account_private
#             # ),
#         })
#         payment = self.fiber1.get_client().send_payment({
#             "invoice": invoice["invoice_address"],
#             # ""
#             # "amount": hex(30 * 100000000),
#             # "keysend": True,
#             # "target_pubkey": fiber3.get_client().node_info()["node_id"],
#             # "tlc_expiry_limit": hex(9000 * 1001),
#             # "final_tlc_expiry_delta": hex(9000 * 1000)
#         })
#         self.fiber1.force_stop()
#         # print(payment)
#         # self.wait_payment_state(self.fiber1, payment["payment_hash"])
#         # CHANNEL_ID = self.fiber1.get_client().list_channels({})["channels"][0]["channel_id"]
#         # tlc = self.fiber1.get_client().add_tlc({
#         #     "channel_id": CHANNEL_ID,
#         #     "amount": hex(1 * 100000001),
#         #     "payment_hash": invoice["invoice"]["data"]["payment_hash"],
#         #     "expiry": hex((int(time.time()) + 10) * 1000),
#         # })
#         # time.sleep(3)
#         # self.get_fibers_balance_message()
