import time

from framework.basic_fiber import FiberTest
from framework.test_fiber import FiberConfigPath


class TestIssue670(FiberTest):
    fiber_version = FiberConfigPath.CURRENT_DEV_DEBUG

    def test_issue_670(self):
        self.start_new_fiber(self.generate_account(1000))
        self.open_channel(self.fiber1, self.fiber2, 1000 * 100000000, 1000 * 100000000)
        preimage = self.generate_random_preimage()
        invoice = (
            self.fibers[2]
            .get_client()
            .new_invoice(
                {
                    "amount": hex(300 * 100000000),
                    "currency": "Fibd",
                    "description": "test invoice generated by node2",
                    "expiry": "0xe10",
                    "final_cltv": "0x28",
                    "payment_preimage": preimage,
                    "hash_algorithm": "ckb_hash",
                }
            )
        )
        # add tlc node1
        CHANNEL_ID1 = self.fiber1.get_client().list_channels({})["channels"][0][
            "channel_id"
        ]
        self.fiber1.get_client().add_tlc(
            {
                "channel_id": CHANNEL_ID1,
                "amount": hex(300 * 100000000),
                "payment_hash": invoice["invoice"]["data"]["payment_hash"],
                "expiry": hex((int(time.time()) + 360000) * 1000),
                "hash_algorithm": "ckb_hash",
            }
        )
