import pytest

from framework.basic_fiber import FiberTest


class TestUdtTypeScript(FiberTest):

    @pytest.mark.skip("repeat")
    def test_white_type_script(self):
        pass

    def test_not_exist_white_type_script(self):
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(100),
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": "sha256",
                "udt_type_script": {
                    "code_hash": self.generate_random_str(64),
                    "hash_type": "data2",
                    "args": "0x12",
                },
            }
        )
        invoice = self.fiber1.get_client().parse_invoice(
            {
                "invoice": invoice["invoice_address"],
            }
        )

    @pytest.mark.skip("repeat")
    def test_none(self):
        pass
