from framework.basic_fiber import FiberTest


class DupInvoice(FiberTest):
    def test_dup_invoice(self):
        for i in range(3):
            self.open_channel(self.fiber1, self.fiber2, 1000 * 100000000, 0)
        # fiber2 生成一个static invoice
        fiber2_invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(1001 * 100000000),
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "hash_algorithm": "sha256",
                "reuse": True,
                "allow_atomic_mpp": True,
            }
        )
        for i in range(2):
            payment = self.fiber1.get_client().send_payment(
                {"invoice": fiber2_invoice["invoice_address"]}
            )
            self.wait_payment_state(
                self.fiber1, payment["payment_hash"], "Success", 120
            )
        fiber2_balance = self.get_fiber_balance(self.fiber2)
        assert fiber2_balance["ckb"]["local_balance"] == 2002 * 100000000
