from unittest import TestCase

import pytest

from framework.basic_fiber import FiberTest


class TestNewInvoice(FiberTest):

    def test_new_invoice(self):
        """
        new invoice 不可以包含payment_preimage ->Both payment_hash and payment_preimage are set
        new invoice 返回结果包含 {"feature": ["ATOMIC_MPP_OPTIONAL"]}
        """
        with pytest.raises(Exception) as exc_info:
            self.fiber1.get_client().new_invoice(
                {
                    "amount": hex(1 * 100000000),
                    "currency": "Fibd",
                    "description": "test invoice generated by node2",
                    "expiry": "0xe10",
                    "payment_preimage": self.generate_random_preimage(),
                    "allow_atomic_mpp": True,
                }
            )
        expected_error_message = "Both payment_hash and payment_preimage are set"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )

        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(1 * 100000000),
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "allow_atomic_mpp": True,
            }
        )
        # todo assert
        assert {"feature": ["ATOMIC_MPP_OPTIONAL"]} in invoice["invoice"]["data"][
            "attrs"
        ]

    def test_illegal_invoice(self):
        """
        cancel invoice
        expired invoice
        """
        self.open_channel(self.fiber1, self.fiber2, 1000 * 100000000, 0, 0, 0)
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(1),
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "allow_atomic_mpp": True,
            }
        )
        self.fiber1.get_client().cancel_invoice(
            {
                "payment_hash": invoice["invoice"]["data"]["payment_hash"],
            }
        )
        self.fiber1.get_client().get_invoice(
            {"payment_hash": invoice["invoice"]["data"]["payment_hash"]}
        )
        with pytest.raises(Exception) as exc_info:
            payment = self.fiber2.get_client().send_payment(
                {"invoice": invoice["invoice_address"], "amp": True}
            )
        expected_error_message = "Failed to build route"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )

        # expiry invoice
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(1),
                "currency": "Fibd",
                "expiry": "0x0",
                "description": "test invoice generated by node2",
                "allow_atomic_mpp": True,
            }
        )
        with pytest.raises(Exception) as exc_info:
            payment = self.fiber2.get_client().send_payment(
                {"invoice": invoice["invoice_address"], "amp": True}
            )
        expected_error_message = "invoice is expired"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )
