from framework.basic_fiber import FiberTest


class TestMutilNodePayment(FiberTest):

    def test_mutil_node_payment(self):
        N = 2
        for i in range(N):
            self.start_new_fiber(self.generate_account(10000))
        for i in range(1, len(self.fibers)):
            self.open_channel(
                self.fiber1, self.fibers[i], 1000 * 100000000, 1000 * 100000000
            )

        atomic_invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(1 * 100000000),
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "hash_algorithm": "sha256",
                "allow_atomic_mpp": True,
            }
        )
        payments = set()
        payment_list = []
        for i in range(1, len(self.fibers)):
            payment = (
                self.fibers[i]
                .get_client()
                .send_payment(
                    {"invoice": atomic_invoice["invoice_address"], "amp": True}
                )
            )
            payments.add(payment["payment_hash"])
            payment_list.append(payment["payment_hash"])
        assert len(payments) == N + 1
        for i in range(len(payment_list)):
            print("payment hash:", payment_list[i])
            self.wait_payment_state(self.fibers[i + 1], payment_list[i])
