from framework.basic_fiber import FiberTest


class TestHashAlgorithm(FiberTest):

    def test_hash_algorithm(self):
        """
        1. none
        2. sha256
        3. ckb_hash
        """
        # none
        for i in range(3):
            self.open_channel(self.fiber1, self.fiber2, 1000 * 100000000, 0)
        # none
        fiber2_invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(1 * 100000000),
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                # "hash_algorithm": "sha256",
                "allow_atomic_mpp": True,
            }
        )
        for i in range(2):
            payment = self.fiber1.get_client().send_payment(
                {"invoice": fiber2_invoice["invoice_address"], "amp": True}
            )
            self.wait_payment_state(
                self.fiber1, payment["payment_hash"], "Success", 120
            )

        # sha256
        fiber2_invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(1 * 100000000),
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "hash_algorithm": "sha256",
                "allow_atomic_mpp": True,
            }
        )
        for i in range(2):
            payment = self.fiber1.get_client().send_payment(
                {"invoice": fiber2_invoice["invoice_address"], "amp": True}
            )
            self.wait_payment_state(
                self.fiber1, payment["payment_hash"], "Success", 120
            )

        # ckb_hash
        fiber2_invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(1 * 100000000),
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "hash_algorithm": "ckb_hash",
                "allow_atomic_mpp": True,
            }
        )
        for i in range(2):
            payment = self.fiber1.get_client().send_payment(
                {"invoice": fiber2_invoice["invoice_address"], "amp": True}
            )
            self.wait_payment_state(
                self.fiber1, payment["payment_hash"], "Success", 120
            )
