import pytest

from framework.basic_fiber import FiberTest


class DupInvoice(FiberTest):
    def test_dup_invoice(self):
        for i in range(3):
            self.open_channel(self.fiber1, self.fiber2, 1000 * 100000000, 0)
        # fiber2 生成一个static invoice
        fiber2_invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(1001 * 100000000),
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "hash_algorithm": "sha256",
                "allow_atomic_mpp": True,
            }
        )

        # send payment without amp
        with pytest.raises(Exception) as exc_info:
            # self.send_invoice_payment(self.fiber1, self.fiber2, 1000 * 100000000 + 10000 - 1)
            self.fiber1.get_client().send_payment(
                {"invoice": fiber2_invoice["invoice_address"]}
            )
        expected_error_message = (
            "It is a AMP invoice, need to set amp flag in SendPayment"
        )
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )

        for i in range(2):
            payment = self.fiber1.get_client().send_payment(
                {"invoice": fiber2_invoice["invoice_address"], "amp": True}
            )
            self.wait_payment_state(
                self.fiber1, payment["payment_hash"], "Success", 120
            )
        fiber2_balance = self.get_fiber_balance(self.fiber2)
        assert fiber2_balance["ckb"]["local_balance"] == 2002 * 100000000
