import time

import pytest

from framework.basic_fiber import FiberTest
from framework.test_fiber import FiberConfigPath


class TestDebugWatchTower(FiberTest):
    fiber_version = FiberConfigPath.CURRENT_TESTNET
    start_fiber_config = {"fiber_watchtower_check_interval_seconds": 5}

    def test_discord_tx(self):
        """
        Returns:
        """
        self.fiber3 = self.start_new_fiber(self.generate_account(1000))
        self.fiber2.stop()
        self.fiber2.prepare(
            {
                "fiber_standalone_watchtower_rpc_url": self.fiber3.get_client().url,
                "fiber_disable_built_in_watchtower": True,
            }
        )
        self.fiber2.start()
        self.open_channel(self.fiber1, self.fiber2, 1000 * 100000000, 1)

        # add tlc node1
        CHANNEL_ID = self.fiber1.get_client().list_channels({})["channels"][0][
            "channel_id"
        ]
        self.fiber1.get_client().add_tlc(
            {
                "channel_id": CHANNEL_ID,
                "amount": hex(300 * 100000000),
                "payment_hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
                "expiry": hex((int(time.time()) + 1500) * 1000),
            }
        )

        time.sleep(1)
        self.fiber1.get_client().shutdown_channel(
            {
                "channel_id": self.fiber1.get_client().list_channels({})["channels"][0][
                    "channel_id"
                ],
                "force": True,
            }
        )
        tx = self.wait_and_check_tx_pool_fee(1000, False)
        self.Miner.miner_until_tx_committed(self.node, tx)
        self.fiber2.stop()
        self.fiber1.stop()
        self.node.getClient().generate_epochs("0x6")

        tx = self.wait_and_check_tx_pool_fee(1000, False, 120 * 5)

        # with pytest.raises(Exception) as exc_info:
        #     tx = self.wait_and_check_tx_pool_fee(1000, False, 120 * 5)
        # expected_error_message = "expected_state"
        # assert expected_error_message in exc_info.value.args[0], (
        #     f"Expected substring '{expected_error_message}' "
        #     f"not found in actual string '{exc_info.value.args[0]}'"
        # )
        # self.fiber2.start()
        # tx = self.wait_and_check_tx_pool_fee(1000, False, 120 * 5)
        # self.fiber1.start()
        # self.open_channel(self.fiber1, self.fiber2, 1000 * 100000000, 1)
        # self.fiber1.get_client().shutdown_channel({
        #     "channel_id": self.fiber1.get_client().list_channels({})["channels"][0][
        #         "channel_id"
        #     ],
        #     "force": True,
        # })
        # tx = self.wait_and_check_tx_pool_fee(1000, False)
        # self.Miner.miner_until_tx_committed(self.node, tx)
        # self.fiber1.stop()
        # self.fiber2.stop()
        # self.node.getClient().generate_epochs("0x6")
        # tx = self.wait_and_check_tx_pool_fee(1000, False, 120 * 5)

    def test_pending_tlc(self):
        self.fiber3 = self.start_new_fiber(self.generate_account(1000))
        self.fiber4 = self.start_new_fiber(self.generate_account(1000))
        self.fiber2.stop()
        self.fiber2.prepare(
            {
                "fiber_standalone_watchtower_rpc_url": self.fiber3.get_client().url,
                "fiber_disable_built_in_watchtower": True,
            }
        )
        self.fiber2.start()
        self.open_channel(self.fiber1, self.fiber2, 1000 * 100000000, 1)
        payment_preimage = self.generate_random_preimage()
        invoice = self.fiber4.get_client().new_invoice(
            {
                "amount": hex(300 * 100000000),
                "currency": "Fibd",
                "description": "test invoice generated by node3",
                "expiry": "0xe10",
                "final_expiry_delta": "0xDFFA0",
                "payment_preimage": payment_preimage,
                # "udt_type_script": self.get_account_udt_script(
                #     self.fiber1.account_private
                # ),
            }
        )
        CHANNEL_ID = self.fiber1.get_client().list_channels({})["channels"][0][
            "channel_id"
        ]
        tlc = self.fiber1.get_client().add_tlc(
            {
                "channel_id": CHANNEL_ID,
                "amount": hex(300 * 100000000),
                "payment_hash": invoice["invoice"]["data"]["payment_hash"],
                "expiry": hex((int(time.time()) + 200) * 1000),
            }
        )
        time.sleep(1)
        self.fiber1.get_client().shutdown_channel(
            {
                "channel_id": CHANNEL_ID,
                "force": True,
            }
        )
        self.fiber2.get_client().remove_tlc(
            {
                "channel_id": CHANNEL_ID,
                "tlc_id": tlc["tlc_id"],
                "reason": {"payment_preimage": payment_preimage},
            }
        )
        tx = self.wait_and_check_tx_pool_fee(1000, False)
        self.Miner.miner_until_tx_committed(self.node, tx)
        self.fiber1.stop()
        self.node.getClient().generate_epochs("0x6", 0)
        tx1 = self.wait_and_check_tx_pool_fee(1000, False, 30 * 5)

        self.Miner.miner_until_tx_committed(self.node, tx)
        time.sleep(5)
        self.node.getClient().generate_epochs("0x6", 0)
        tx2 = self.wait_and_check_tx_pool_fee(1000, False, 20 * 5)
        print("tx1:", tx1)
        print("tx2:", tx2)

    @pytest.mark.skip("expire tlc too bigger")
    def test_expire_tlc(self):
        self.fiber3 = self.start_new_fiber(self.generate_account(1000))
        self.fiber4 = self.start_new_fiber(self.generate_account(1000))
        self.fiber2.stop()
        self.fiber2.prepare(
            {
                "fiber_standalone_watchtower_rpc_url": self.fiber3.get_client().url,
                "fiber_disable_built_in_watchtower": True,
            }
        )
        self.fiber2.start()
        self.open_channel(self.fiber1, self.fiber2, 1000 * 100000000, 1000 * 100000000)
        payment_preimage = self.generate_random_preimage()
        invoice = self.fiber4.get_client().new_invoice(
            {
                "amount": hex(300 * 100000000),
                "currency": "Fibd",
                "description": "test invoice generated by node3",
                "expiry": "0xe10",
                "final_expiry_delta": "0xDFFA0",
                "payment_preimage": payment_preimage,
                # "udt_type_script": self.get_account_udt_script(
                #     self.fiber1.account_private
                # ),
            }
        )
        CHANNEL_ID = self.fiber1.get_client().list_channels({})["channels"][0][
            "channel_id"
        ]
        tlc = self.fiber2.get_client().add_tlc(
            {
                "channel_id": CHANNEL_ID,
                "amount": hex(300 * 100000000),
                "payment_hash": invoice["invoice"]["data"]["payment_hash"],
                "expiry": hex((int(time.time()) + 10) * 1000),
            }
        )
        time.sleep(1)
        self.fiber2.get_client().shutdown_channel(
            {
                "channel_id": CHANNEL_ID,
                "force": True,
            }
        )
        # self.fiber2.get_client().remove_tlc({
        #     "channel_id": CHANNEL_ID,
        #     "tlc_id": tlc["tlc_id"],
        #     "reason": {"payment_preimage": payment_preimage},
        # })
        tx = self.wait_and_check_tx_pool_fee(1000, False)
        self.Miner.miner_until_tx_committed(self.node, tx)
        self.fiber1.stop()
        self.node.getClient().generate_epochs("0x4", 0)
        tx1 = self.wait_and_check_tx_pool_fee(1000, False, 40 * 5)

        self.Miner.miner_until_tx_committed(self.node, tx)
        time.sleep(5)
        self.node.getClient().generate_epochs("0x6", 0)
        tx2 = self.wait_and_check_tx_pool_fee(1000, False, 20 * 5)
        print("tx1:", tx1)
        print("tx2:", tx2)